In [1]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [2]:
sent = [
    "The sun is shining brightly today.",
    "I need to buy groceries after work.",
    "She finished reading the book last night.",
    "The cat slept on the windowsill.",
    "Coffee is my favorite morning drink.",
]

In [3]:
sent

['The sun is shining brightly today.',
 'I need to buy groceries after work.',
 'She finished reading the book last night.',
 'The cat slept on the windowsill.',
 'Coffee is my favorite morning drink.']

In [4]:
vocab_size = 10000

In [5]:
one_hot_rep = [one_hot(words,vocab_size) for words in sent]
one_hot_rep

[[8408, 2173, 7249, 1315, 7691, 2282],
 [636, 3699, 2607, 8502, 9084, 2405, 9867],
 [6826, 2018, 9242, 8408, 4578, 5967, 1112],
 [8408, 61, 77, 3913, 8408, 4659],
 [2878, 7249, 2319, 1210, 9895, 3192]]

In [7]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, maxlen = sent_length, padding = 'pre')

In [8]:
print(embedded_docs)

[[   0    0 8408 2173 7249 1315 7691 2282]
 [   0  636 3699 2607 8502 9084 2405 9867]
 [   0 6826 2018 9242 8408 4578 5967 1112]
 [   0    0 8408   61   77 3913 8408 4659]
 [   0    0 2878 7249 2319 1210 9895 3192]]


In [9]:
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length = sent_length))

model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 145ms/step


array([[[ 0.03934741,  0.02563358, -0.03686788,  0.03056133,
          0.02943149,  0.01513913,  0.04266248,  0.00769204,
          0.01005377, -0.01157112],
        [ 0.03934741,  0.02563358, -0.03686788,  0.03056133,
          0.02943149,  0.01513913,  0.04266248,  0.00769204,
          0.01005377, -0.01157112],
        [-0.04251678, -0.00865209,  0.01628963, -0.02139655,
          0.04237788, -0.00947024, -0.04388647, -0.03356697,
          0.01591196,  0.02046794],
        [-0.00109762, -0.04607103,  0.04225012,  0.04402738,
          0.03315028, -0.02660509,  0.04066995,  0.02570749,
          0.04799351, -0.01380565],
        [-0.02587739, -0.01295479,  0.03850513,  0.03641405,
          0.00312684, -0.00397398, -0.02806394,  0.0226743 ,
         -0.0334563 , -0.04296471],
        [ 0.01226284, -0.04359704, -0.0162065 ,  0.02525474,
          0.00516566, -0.01694621,  0.02404156,  0.01196972,
          0.03702488, -0.02393342],
        [-0.03235118, -0.0228027 ,  0.02883985, -0.0